# Generated by Django 5.1.7 on 2025-03-25 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("year", models.PositiveIntegerField()),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("poster", models.ImageField(upload_to="movie/posters")),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="movie/videos"),
                ),
                (
                    "actors",
                    models.ManyToManyField(related_name="movies", to="common.actor"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="common.director",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="movies", to="common.genre"),
                ),
            ],
        ),
    ]
