# Generated by Django 5.1.7 on 2025-04-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("movie", "0002_alter_movie_genres_alter_movie_poster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movies",
                to="common.director",
            ),
        ),
    ]
