# Generated by Django 5.1.7 on 2025-04-04 09:40

import common.models.base_content
import common.models.base_episode
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Serial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("year", models.PositiveIntegerField()),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        upload_to=common.models.base_content._poster_upload_path
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(related_name="serials", to="common.actor"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serials",
                        to="common.director",
                    ),
                ),
                ("genres", models.ManyToManyField(to="common.genre")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SerialEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("episode_number", models.PositiveIntegerField()),
                (
                    "video",
                    models.FileField(
                        upload_to=common.models.base_episode._episode_upload_path
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="serial.serial"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
