# Generated by Django 5.1.7 on 2025-04-10 19:34

import domain.models.movie
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "surname"), name="actor_unique_name_surname"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "surname"), name="director_unique_name_surname"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("year", models.PositiveIntegerField()),
                ("rating", models.FloatField()),
                ("duration", models.PositiveIntegerField()),
                (
                    "poster",
                    models.FileField(
                        upload_to=domain.models.movie.movie_poster_upload_path
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=domain.models.movie.movie_video_upload_path,
                    ),
                ),
                ("actors", models.ManyToManyField(to="domain.actor")),
                ("director", models.ManyToManyField(to="domain.director")),
                ("genres", models.ManyToManyField(to="domain.genre")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
