# Generated by Django 5.1.7 on 2025-04-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="directors",
        ),
    ]
